MVCProject/Controllers/PropertiesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCProject.DAL;
using MVCProject.Models;
using MVCProject.ViewModels;

namespace MVCProject.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly AppDbContext _context;
        public PropertiesController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(PropertiesVM vm)
        {
            var query = _context.Products
                .Include(p => p.Category)
                .Include(p => p.ProductFeatures)
                    .ThenInclude(pf => pf.Feature)
                .Include(p => p.Dealer)
                .Include(p => p.Images)
                .AsQueryable();

           
            if (!string.IsNullOrEmpty(vm.City))
                query = query.Where(p => p.City == vm.City);

            if (!string.IsNullOrEmpty(vm.Status))
                query = query.Where(p => p.Status == vm.Status);

            
            if (vm.SelectedFeatures != null && vm.SelectedFeatures.Any())
                query = query.Where(p =>
                    p.ProductFeatures.Any(pf => vm.SelectedFeatures.Contains(pf.FeatureID)));

           
            var products = await query.ToListAsync();

            
            ViewBag.Cities = await _context.Products
                .Select(p => p.City)
                .Where(c => !string.IsNullOrEmpty(c))
                .Distinct()
                .ToListAsync();

            ViewBag.Statuses = await _context.Products
                .Select(p => p.Status)
                .Where(s => !string.IsNullOrEmpty(s))
                .Distinct()
                .ToListAsync();

            ViewBag.Features = await _context.Features.ToListAsync();

            return View(products);
        }


        [Route("properties/detail/{id}")]
        public async Task<IActionResult> Detail(int? id, PropertiesVM vm)
        {
            if (id == null || id < 1) return BadRequest();

           
            Product product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.ProductFeatures)
                    .ThenInclude(pf => pf.Feature)
                .Include(p => p.Dealer)
                .Include(p => p.AdditionalDetails)
                .Include(p => p.Images)
                .FirstOrDefaultAsync(p => p.ID == id);

            if (product == null) return NotFound();

           
            var query = _context.Products.AsQueryable();

            if (!string.IsNullOrEmpty(vm.City))
                query = query.Where(p => p.City == vm.City);

            if (!string.IsNullOrEmpty(vm.Status))
                query = query.Where(p => p.Status == vm.Status);

          
            if (vm.SelectedFeatures != null && vm.SelectedFeatures.Any())
                query = query.Where(p => p.ProductFeatures.Any(pf => vm.SelectedFeatures.Contains(pf.FeatureID)));

            List<Product> similarProducts = await query
                .Where(p => p.CategoryID == product.CategoryID && p.ID != product.ID)
                .Include(p => p.Images)
                .Take(4)
                .ToListAsync();

            
            DetailVM detailVM = new DetailVM
            {
                Product = product,
                Dealer = product.Dealer,
                AdditionalDetail = product.AdditionalDetails,
                Feature = product.ProductFeatures.Select(pf => pf.Feature).ToList(),
                SimilarProperties = similarProducts
            };

          
            ViewBag.Cities = await _context.Products
                .Select(p => p.City)
                .Where(c => !string.IsNullOrEmpty(c))
                .Distinct()
                .ToListAsync();

            ViewBag.Statuses = await _context.Products
                .Select(p => p.Status)
                .Where(s => !string.IsNullOrEmpty(s))
                .Distinct()
                .ToListAsync();

            ViewBag.Features = await _context.Features.ToListAsync();

            return View(detailVM);
        }

    }
}

MVCProject/Views/Properties/Index.cshtml
<div class="properties-area recent-property" style="background-color: #FFF;">
    <div class="container">
        <div class="row">
            <div class="col-md-9 padding-top-40 properties-page">
                <div class="section clear">
                    <div id="list-type" class="proerty-th">
                        @foreach (Product products in Model)
                        {
                            <div class="col-sm-6 col-md-4 p0 mb-4">
                                <div class="box-two proerty-item shadow-sm border rounded-lg overflow-hidden">
                                    <div class="item-thumb">
                                        <a asp-controller="Properties" asp-action="Detail" asp-route-id="@products.ID">
                                            <img src="~/assets/img/demo/@products.Images.FirstOrDefault()?.Filename" class="img-fluid">
                                        </a>
                                    </div>
                                    <div class="item-entry overflow p-3">
                                        <h5><a href="property-1.html" class="text-dark font-weight-bold">@products.Name</a></h5>
                                        <div class="dot-hr"></div>
                                        <span class="pull-left"><b>Area:</b> @products.Area</span>
                                        <span class="proerty-price pull-right text-success">$ @products.Price</span>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>

                <div class="section">
                    <div class="pull-right">
                        <div class="pagination">
                            <ul>
                                <li><a href="#">Prev</a></li>
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">Next</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Smart Search Partial View burada yerləşir -->
            <div class="col-md-3">
                @await Html.PartialAsync("SearchPartialView")
            </div>

            <!-- Recommended bölməsi burada Smart Search-in altına gəlir -->
            <div class="col-md-3">
                <div class="panel panel-default sidebar-menu wow fadeInRight animated">
                    <div class="panel-heading">
                        <h3 class="panel-title font-weight-bold">Recommended</h3>
                    </div>
                    <div class="panel-body recent-property-widget">
                        <ul>
                            <li class="mb-3">
                                <div class="col-md-3 col-sm-3 col-xs-3 blg-thumb p0">
                                    <a href="single.html"><img src="~/assets/img/demo/small-property-2.jpg" class="img-fluid"></a>
                                </div>
                                <div class="col-md-8 col-sm-8 col-xs-8 blg-entry">
                                    <h6><a href="single.html">Super nice villa</a></h6>
                                    <span class="property-price text-success">3000000$</span>
                                </div>
                            </li>
                            <li class="mb-3">
                                <div class="col-md-3 col-sm-3 col-xs-3 blg-thumb p0">
                                    <a href="single.html"><img src="~/assets/img/demo/small-property-1.jpg" class="img-fluid"></a>
                                </div>
                                <div class="col-md-8 col-sm-8 col-xs-8 blg-entry">
                                    <h6><a href="single.html">Super nice villa</a></h6>
                                    <span class="property-price text-success">3000000$</span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>