MVCProject/Controllers/FAQController.cs
using Microsoft.AspNetCore.Mvc;
using MVCProject.DAL;
using MVCProject.Models;

namespace MVCProject.Controllers
{
    public class FAQController : Controller
    {
        private readonly AppDbContext _context;

        public FAQController(AppDbContext context)
        {
            _context = context;
        }

        public ActionResult Index()
        {
            List<FAQ> faqs = _context.FAQs.ToList();
            return View(faqs);
        }
    }
}

MVCProject/Controllers/TermController.cs
using Microsoft.AspNetCore.Mvc;
using MVCProject.DAL;
using MVCProject.Models;
using System.Runtime.CompilerServices;

namespace MVCProject.Controllers
{
    public class TermController : Controller
    {
        private readonly AppDbContext _context;
        public TermController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Term> terms = _context.Terms.ToList();
            return View(terms);
        }
        
    }
}

MVCProject/Views/Shared/Components/Footer/Default.cshtml
<!-- Footer Start -->
<div class="footer-area">
    <div class="footer">
        <div class="container">
            <div class="row">
                <!-- About us -->
                <div class="col-md-3 col-sm-6 wow fadeInRight animated">
                    <div class="single-footer">
                        <h4>About us</h4>
                        <div class="footer-title-line"></div>
                        <img src="~/assets/img/@Model.Settings["Logo"]" alt="" class="wow pulse" data-wow-delay="1s">
                        <p>@Model.Settings["Description"]</p>
                        <ul class="footer-adress">
                            <li><i class="pe-7s-map-marker strong"></i> @Model.Settings["Address"]</li>
                            <li><i class="pe-7s-mail strong"></i> @Model.Settings["Email"]</li>
                            <li><i class="pe-7s-call strong"></i> @Model.Settings["Phone"]</li>
                        </ul>
                    </div>
                </div>

                <!-- Quick links -->
                <div class="col-md-3 col-sm-6 wow fadeInRight animated">
                    <div class="single-footer">
                        <h4>Quick links</h4>
                        <div class="footer-title-line"></div>
                        <ul class="footer-menu">
                            <li><a asp-controller="Properties" asp-action="Index">Properties</a></li>
                            <li><a href="#">Services</a></li>
                            <li><a href="#">Submit property</a></li>
                            <li><a asp-controller="Contact" asp-action="Index">Contact us</a></li>
                            <li><a asp-controller="FAQ" asp-action="Index">FAQ</a></li>
                            <li><a asp-controller="Term" asp-action="Index">Terms</a></li>
                        </ul>
                    </div>
                </div>

                <!-- Last News -->
                <div class="col-md-3 col-sm-6 wow fadeInRight animated">
                    <div class="single-footer">
                        <h4>Last News</h4>
                        <div class="footer-title-line"></div>
                        <ul class="footer-blog">
                            @foreach (Product product in Model.Products)
                            {
                                <li>
                                    <div class="col-md-3 col-sm-4 col-xs-4 blg-thumb p0">
                                        <a href="#">
                                            <img src="~/assets/img/demo/@product.Images.FirstOrDefault()?.Filename" alt="@product.Name" />
                                        </a>
                                        <span class="blg-date">@DateTime.Now.ToString("dd-MM-yyyy")</span>
                                    </div>
                                    <div class="col-md-8 col-sm-8 col-xs-8 blg-entry">
                                        <h6><a href="#">@product.Name</a></h6>
                                        <p style="line-height: 17px; padding: 8px 2px;">
                                            @(product.Description?.Length > 40 ? product.Description.Substring(0, 40) + "..." : product.Description)
                                        </p>
                                    </div>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
                <!-- Newsletter -->
                <div class="col-md-3 col-sm-6 wow fadeInRight animated">
                    <div class="single-footer news-letter">
                        <h4>Stay in touch</h4>
                        <div class="footer-title-line"></div>
                        <p>Stay in touch with us</p>
                        <form>
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="E-mail ... ">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary subscribe" type="button">
                                        <i class="pe-7s-paper-plane pe-2x"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                        <div class="social pull-right">
                            <ul>
                                <li><a class="wow fadeInUp animated" href="@Model.Settings["Twitter"]"><i class="fa fa-twitter"></i></a></li>
                                <li><a class="wow fadeInUp animated" href="@Model.Settings["Facebook"]"><i class="fa fa-facebook"></i></a></li>
                                <li><a class="wow fadeInUp animated" href="@Model.Settings["Instagram"]"><i class="fa fa-instagram"></i></a></li>
                                <li><a class="wow fadeInUp animated" href="@Model.Settings["LinkedIn"]"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="footer-copy text-center">
        <div class="container">
            <div class="row">
                <div class="pull-left">
                    <span>(C) <a>KimaroTheme</a>, All rights reserved 2016</span>
                </div>
                <div class="bottom-menu pull-right">
                    <ul>
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Properties" asp-action="Index">Properties</a></li>
                        <li><a asp-controller="FAQ" asp-action="Index">Faq</a></li>
                        <li><a asp-controller="Term" asp-action="Index">Terms</a></li>
                        <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
                        
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->